# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

Post.destroy_all
Bookmark.destroy_all
User.destroy_all

mana = User.create!(email: "mana@me.com", password: "secret", name: "Mana", location: "ヘルシンキ", description:"フィンランドのヘルシンキ在住。20代 ムーミンが好き", avatar:"https://iconbu.com/wp-content/uploads/2023/09/%E3%83%91%E3%82%BD%E3%82%B3%E3%83%B3%E5%85%8E%E3%81%95%E3%82%93.jpg")
tony = User.create!(email: "tony@me.com", password: "secret", name: "Tony", location: "ハノイ", description:"ハノイ在住歴5年　趣味は動物と触れ合うこと", avatar:"https://www.la-comic-illust.top/wp-content/uploads/2021/01/face4.png")
mila = User.create!(email: "mila@me.com", password: "secret", name: "Mila", location: "ミラノ", description:"イタリアのミラノ在住。好きな食べ物はパスタとピザ", avatar:"https://iconbu.com/wp-content/uploads/2020/01/%E3%83%9A%E3%83%B3%E3%82%AE%E3%83%B3%E3%81%AE%E3%82%A2%E3%82%A4%E3%82%B3%E3%83%B3.jpg")
milo = User.create!(email: "milo@me.com", password: "secret", name: "Milo", location: "シドニー", description:"", avatar:"https://iconbu.com/wp-content/uploads/2020/03/%E3%83%91%E3%83%B3%E3%83%80.jpg")
ron = User.create!(email: "ron@me.com", password: "secret", name: "Ron", location: "デリー", description:"高校生のときに、インドのデリーに引越し。スパイスカレー作りが得意。", avatar:"https://iconbu.com/wp-content/uploads/2022/04/%E3%81%BE%E3%81%A3%E3%81%9F%E3%82%8A%E3%82%B7%E3%83%A3%E3%83%81%E3%81%95%E3%82%93.jpg")

Bookmark.create!(name: "フィンランド", user: tony)
Bookmark.create!(name: "オーストラリア", user: tony)

Post.create!(title: "ヘルシンキの幼稚園に通い始めました", location: "ヘルシンキ", category: "学校", user: mana, description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugit nemo fugiat error illum suscipit dolor! Molestiae natus eum fugit quam aliquam quisquam cumque laborum placeat, dicta quis, dolorum, odit animi.
  Illum recusandae accusamus nam magni, nulla labore pariatur eaque maiores doloremque quae? Reiciendis voluptatum voluptatem praesentium nam odio adipisci autem assumenda voluptatibus similique. Optio, dignissimos sunt itaque delectus iste explicabo.
  Laboriosam fugit, ullam illo autem corporis nihil. Eos voluptas facilis at consectetur nam quia sit perferendis asperiores similique nesciunt, impedit dolorum mollitia, incidunt corrupti optio exercitationem sunt illo ipsum saepe.
  Accusantium eaque officiis voluptatibus quaerat alias, quo vero est nisi, aliquid, fugit dolor aliquam commodi laudantium velit. Consectetur nihil totam, nam eligendi exercitationem in quibusdam neque rerum. Quia, ducimus eum?
  Nostrum assumenda quasi fuga repellat ipsam temporibus illum corrupti, tempore quos deserunt numquam atque, dicta, animi unde reiciendis? Vitae, rem! Iure provident voluptatibus autem dolorum facilis dolores dolore sunt dolor!
  Deserunt possimus sed laudantium quos pariatur animi doloribus, in cumque praesentium. Laborum velit sapiente ratione. Similique, facere voluptatibus iste dolorum laborum nisi est quas veniam quo, consectetur perferendis sint illum.
  Numquam sunt ad soluta porro delectus, temporibus facere dolorem sit? Corporis consequatur neque et perferendis architecto dolorem aspernatur nostrum natus esse eius quisquam, ipsam tempore cumque ex qui ut debitis?
  Temporibus voluptatibus at ipsam quos itaque aut porro, quibusdam accusamus? Dicta est architecto itaque nam eius, facere molestiae! Minima, dolor eos. Magnam ad praesentium consectetur, deserunt consequatur ex nisi saepe?
  Aspernatur excepturi eius minus non repellendus quibusdam culpa perspiciatis enim amet, tempora impedit. Quidem repudiandae vel corrupti architecto officia, dolor accusantium quis temporibus eaque dignissimos, voluptas debitis hic in esse.
  Delectus debitis, voluptatibus perspiciatis quasi beatae rem omnis ad animi modi ducimus, libero illo quaerat eos cupiditate? Reiciendis enim nam labore, corporis provident dolorem tempora vel tenetur culpa a magnam.
  Velit quas, at possimus culpa consequatur, suscipit itaque amet deserunt quos quaerat voluptate facere eligendi! Laudantium error, veritatis mollitia quis commodi quaerat magni nisi, perferendis, nesciunt quasi repellat consequuntur deleniti!
  Quidem tempora possimus ab, esse quae ut iste eaque optio exercitationem velit reprehenderit quo! Hic saepe sint at quasi, cumque iste! Voluptatibus cupiditate esse quasi officiis harum mollitia dignissimos ullam.
  Blanditiis repellat reiciendis praesentium officia error illum, sit eaque veritatis quo vitae qui minima et quod dolorem perspiciatis sed impedit incidunt eius excepturi quos aliquam beatae numquam. Illum, iusto deleniti.
  Sit odio voluptatum dolorem porro consequatur alias laudantium eius magni, praesentium rerum ea tenetur atque quidem et temporibus, perspiciatis ipsum quibusdam asperiores soluta ipsa expedita tempora! Distinctio odit aspernatur accusamus.
  Adipisci voluptate labore repudiandae aliquam minima magnam quidem mollitia tenetur commodi. Itaque repellendus architecto eius nisi. Illo aliquid assumenda enim et ratione dicta vel tempore mollitia eaque quibusdam, rerum natus!
  Atque sunt accusantium porro vitae, in error nisi molestias corrupti accusamus necessitatibus dolorem, doloremque labore nam minus explicabo perferendis. Quo at architecto iste eligendi tempora ea, laborum sapiente eius earum.
  Tempora enim cupiditate ducimus optio voluptates deserunt quidem inventore illum sequi amet, reprehenderit molestias adipisci aliquam magni autem voluptate, excepturi, quia recusandae illo cumque at rem? Ipsam, ipsa. Aliquam, repudiandae!
  Molestias dolorem, temporibus, quae earum magnam, praesentium repudiandae labore delectus necessitatibus fuga quis quasi! Nulla ad, odio distinctio doloremque, praesentium impedit modi veritatis non inventore unde, nobis ea aliquid perferendis.
  Quibusdam aliquid cum placeat magni delectus natus at laboriosam, maiores labore nulla ex sed ullam temporibus culpa veniam odio. Aut ea modi quis maxime facere asperiores in necessitatibus, quisquam doloremque.
  Quibusdam dolor expedita, commodi asperiores saepe odit, beatae a modi optio ea possimus. Natus at optio velit dolores amet sed rerum? Sit officia nesciunt, harum aliquid blanditiis praesentium pariatur rerum!")
Post.create!(title: "ミラノの日本語学校について", location: "ミラノ", category: "学校", user: mila, description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugit nemo fugiat error illum suscipit dolor! Molestiae natus eum fugit quam aliquam quisquam cumque laborum placeat, dicta quis, dolorum, odit animi.
  Illum recusandae accusamus nam magni, nulla labore pariatur eaque maiores doloremque quae? Reiciendis voluptatum voluptatem praesentium nam odio adipisci autem assumenda voluptatibus similique. Optio, dignissimos sunt itaque delectus iste explicabo.
  Laboriosam fugit, ullam illo autem corporis nihil. Eos voluptas facilis at consectetur nam quia sit perferendis asperiores similique nesciunt, impedit dolorum mollitia, incidunt corrupti optio exercitationem sunt illo ipsum saepe.
  Accusantium eaque officiis voluptatibus quaerat alias, quo vero est nisi, aliquid, fugit dolor aliquam commodi laudantium velit. Consectetur nihil totam, nam eligendi exercitationem in quibusdam neque rerum. Quia, ducimus eum?
  Nostrum assumenda quasi fuga repellat ipsam temporibus illum corrupti, tempore quos deserunt numquam atque, dicta, animi unde reiciendis? Vitae, rem! Iure provident voluptatibus autem dolorum facilis dolores dolore sunt dolor!
  Deserunt possimus sed laudantium quos pariatur animi doloribus, in cumque praesentium. Laborum velit sapiente ratione. Similique, facere voluptatibus iste dolorum laborum nisi est quas veniam quo, consectetur perferendis sint illum.
  Numquam sunt ad soluta porro delectus, temporibus facere dolorem sit? Corporis consequatur neque et perferendis architecto dolorem aspernatur nostrum natus esse eius quisquam, ipsam tempore cumque ex qui ut debitis?
  Temporibus voluptatibus at ipsam quos itaque aut porro, quibusdam accusamus? Dicta est architecto itaque nam eius, facere molestiae! Minima, dolor eos. Magnam ad praesentium consectetur, deserunt consequatur ex nisi saepe?
  Aspernatur excepturi eius minus non repellendus quibusdam culpa perspiciatis enim amet, tempora impedit. Quidem repudiandae vel corrupti architecto officia, dolor accusantium quis temporibus eaque dignissimos, voluptas debitis hic in esse.
  Delectus debitis, voluptatibus perspiciatis quasi beatae rem omnis ad animi modi ducimus, libero illo quaerat eos cupiditate? Reiciendis enim nam labore, corporis provident dolorem tempora vel tenetur culpa a magnam.
  Velit quas, at possimus culpa consequatur, suscipit itaque amet deserunt quos quaerat voluptate facere eligendi! Laudantium error, veritatis mollitia quis commodi quaerat magni nisi, perferendis, nesciunt quasi repellat consequuntur deleniti!
  Quidem tempora possimus ab, esse quae ut iste eaque optio exercitationem velit reprehenderit quo! Hic saepe sint at quasi, cumque iste! Voluptatibus cupiditate esse quasi officiis harum mollitia dignissimos ullam.
  Blanditiis repellat reiciendis praesentium officia error illum, sit eaque veritatis quo vitae qui minima et quod dolorem perspiciatis sed impedit incidunt eius excepturi quos aliquam beatae numquam. Illum, iusto deleniti.
  Sit odio voluptatum dolorem porro consequatur alias laudantium eius magni, praesentium rerum ea tenetur atque quidem et temporibus, perspiciatis ipsum quibusdam asperiores soluta ipsa expedita tempora! Distinctio odit aspernatur accusamus.
  Adipisci voluptate labore repudiandae aliquam minima magnam quidem mollitia tenetur commodi. Itaque repellendus architecto eius nisi. Illo aliquid assumenda enim et ratione dicta vel tempore mollitia eaque quibusdam, rerum natus!
  Atque sunt accusantium porro vitae, in error nisi molestias corrupti accusamus necessitatibus dolorem, doloremque labore nam minus explicabo perferendis. Quo at architecto iste eligendi tempora ea, laborum sapiente eius earum.
  Tempora enim cupiditate ducimus optio voluptates deserunt quidem inventore illum sequi amet, reprehenderit molestias adipisci aliquam magni autem voluptate, excepturi, quia recusandae illo cumque at rem? Ipsam, ipsa. Aliquam, repudiandae!
  Molestias dolorem, temporibus, quae earum magnam, praesentium repudiandae labore delectus necessitatibus fuga quis quasi! Nulla ad, odio distinctio doloremque, praesentium impedit modi veritatis non inventore unde, nobis ea aliquid perferendis.
  Quibusdam aliquid cum placeat magni delectus natus at laboriosam, maiores labore nulla ex sed ullam temporibus culpa veniam odio. Aut ea modi quis maxime facere asperiores in necessitatibus, quisquam doloremque.
  Quibusdam dolor expedita, commodi asperiores saepe odit, beatae a modi optio ea possimus. Natus at optio velit dolores amet sed rerum? Sit officia nesciunt, harum aliquid blanditiis praesentium pariatur rerum!")
Post.create!(title: "ハノイの小学校入学手続きについて", location: "ハノイ", category: "学校", user: tony, description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugit nemo fugiat error illum suscipit dolor! Molestiae natus eum fugit quam aliquam quisquam cumque laborum placeat, dicta quis, dolorum, odit animi.
  Illum recusandae accusamus nam magni, nulla labore pariatur eaque maiores doloremque quae? Reiciendis voluptatum voluptatem praesentium nam odio adipisci autem assumenda voluptatibus similique. Optio, dignissimos sunt itaque delectus iste explicabo.
  Laboriosam fugit, ullam illo autem corporis nihil. Eos voluptas facilis at consectetur nam quia sit perferendis asperiores similique nesciunt, impedit dolorum mollitia, incidunt corrupti optio exercitationem sunt illo ipsum saepe.
  Accusantium eaque officiis voluptatibus quaerat alias, quo vero est nisi, aliquid, fugit dolor aliquam commodi laudantium velit. Consectetur nihil totam, nam eligendi exercitationem in quibusdam neque rerum. Quia, ducimus eum?
  Nostrum assumenda quasi fuga repellat ipsam temporibus illum corrupti, tempore quos deserunt numquam atque, dicta, animi unde reiciendis? Vitae, rem! Iure provident voluptatibus autem dolorum facilis dolores dolore sunt dolor!
  Deserunt possimus sed laudantium quos pariatur animi doloribus, in cumque praesentium. Laborum velit sapiente ratione. Similique, facere voluptatibus iste dolorum laborum nisi est quas veniam quo, consectetur perferendis sint illum.
  Numquam sunt ad soluta porro delectus, temporibus facere dolorem sit? Corporis consequatur neque et perferendis architecto dolorem aspernatur nostrum natus esse eius quisquam, ipsam tempore cumque ex qui ut debitis?
  Temporibus voluptatibus at ipsam quos itaque aut porro, quibusdam accusamus? Dicta est architecto itaque nam eius, facere molestiae! Minima, dolor eos. Magnam ad praesentium consectetur, deserunt consequatur ex nisi saepe?
  Aspernatur excepturi eius minus non repellendus quibusdam culpa perspiciatis enim amet, tempora impedit. Quidem repudiandae vel corrupti architecto officia, dolor accusantium quis temporibus eaque dignissimos, voluptas debitis hic in esse.
  Delectus debitis, voluptatibus perspiciatis quasi beatae rem omnis ad animi modi ducimus, libero illo quaerat eos cupiditate? Reiciendis enim nam labore, corporis provident dolorem tempora vel tenetur culpa a magnam.
  Velit quas, at possimus culpa consequatur, suscipit itaque amet deserunt quos quaerat voluptate facere eligendi! Laudantium error, veritatis mollitia quis commodi quaerat magni nisi, perferendis, nesciunt quasi repellat consequuntur deleniti!
  Quidem tempora possimus ab, esse quae ut iste eaque optio exercitationem velit reprehenderit quo! Hic saepe sint at quasi, cumque iste! Voluptatibus cupiditate esse quasi officiis harum mollitia dignissimos ullam.
  Blanditiis repellat reiciendis praesentium officia error illum, sit eaque veritatis quo vitae qui minima et quod dolorem perspiciatis sed impedit incidunt eius excepturi quos aliquam beatae numquam. Illum, iusto deleniti.
  Sit odio voluptatum dolorem porro consequatur alias laudantium eius magni, praesentium rerum ea tenetur atque quidem et temporibus, perspiciatis ipsum quibusdam asperiores soluta ipsa expedita tempora! Distinctio odit aspernatur accusamus.
  Adipisci voluptate labore repudiandae aliquam minima magnam quidem mollitia tenetur commodi. Itaque repellendus architecto eius nisi. Illo aliquid assumenda enim et ratione dicta vel tempore mollitia eaque quibusdam, rerum natus!
  Atque sunt accusantium porro vitae, in error nisi molestias corrupti accusamus necessitatibus dolorem, doloremque labore nam minus explicabo perferendis. Quo at architecto iste eligendi tempora ea, laborum sapiente eius earum.
  Tempora enim cupiditate ducimus optio voluptates deserunt quidem inventore illum sequi amet, reprehenderit molestias adipisci aliquam magni autem voluptate, excepturi, quia recusandae illo cumque at rem? Ipsam, ipsa. Aliquam, repudiandae!
  Molestias dolorem, temporibus, quae earum magnam, praesentium repudiandae labore delectus necessitatibus fuga quis quasi! Nulla ad, odio distinctio doloremque, praesentium impedit modi veritatis non inventore unde, nobis ea aliquid perferendis.
  Quibusdam aliquid cum placeat magni delectus natus at laboriosam, maiores labore nulla ex sed ullam temporibus culpa veniam odio. Aut ea modi quis maxime facere asperiores in necessitatibus, quisquam doloremque.
  Quibusdam dolor expedita, commodi asperiores saepe odit, beatae a modi optio ea possimus. Natus at optio velit dolores amet sed rerum? Sit officia nesciunt, harum aliquid blanditiis praesentium pariatur rerum!")
Post.create!(title: "デリーでの高校入学試験について", location: "デリー", category: "学校", user: ron, description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugit nemo fugiat error illum suscipit dolor! Molestiae natus eum fugit quam aliquam quisquam cumque laborum placeat, dicta quis, dolorum, odit animi.
  Illum recusandae accusamus nam magni, nulla labore pariatur eaque maiores doloremque quae? Reiciendis voluptatum voluptatem praesentium nam odio adipisci autem assumenda voluptatibus similique. Optio, dignissimos sunt itaque delectus iste explicabo.
  Laboriosam fugit, ullam illo autem corporis nihil. Eos voluptas facilis at consectetur nam quia sit perferendis asperiores similique nesciunt, impedit dolorum mollitia, incidunt corrupti optio exercitationem sunt illo ipsum saepe.
  Accusantium eaque officiis voluptatibus quaerat alias, quo vero est nisi, aliquid, fugit dolor aliquam commodi laudantium velit. Consectetur nihil totam, nam eligendi exercitationem in quibusdam neque rerum. Quia, ducimus eum?
  Nostrum assumenda quasi fuga repellat ipsam temporibus illum corrupti, tempore quos deserunt numquam atque, dicta, animi unde reiciendis? Vitae, rem! Iure provident voluptatibus autem dolorum facilis dolores dolore sunt dolor!
  Deserunt possimus sed laudantium quos pariatur animi doloribus, in cumque praesentium. Laborum velit sapiente ratione. Similique, facere voluptatibus iste dolorum laborum nisi est quas veniam quo, consectetur perferendis sint illum.
  Numquam sunt ad soluta porro delectus, temporibus facere dolorem sit? Corporis consequatur neque et perferendis architecto dolorem aspernatur nostrum natus esse eius quisquam, ipsam tempore cumque ex qui ut debitis?
  Temporibus voluptatibus at ipsam quos itaque aut porro, quibusdam accusamus? Dicta est architecto itaque nam eius, facere molestiae! Minima, dolor eos. Magnam ad praesentium consectetur, deserunt consequatur ex nisi saepe?
  Aspernatur excepturi eius minus non repellendus quibusdam culpa perspiciatis enim amet, tempora impedit. Quidem repudiandae vel corrupti architecto officia, dolor accusantium quis temporibus eaque dignissimos, voluptas debitis hic in esse.
  Delectus debitis, voluptatibus perspiciatis quasi beatae rem omnis ad animi modi ducimus, libero illo quaerat eos cupiditate? Reiciendis enim nam labore, corporis provident dolorem tempora vel tenetur culpa a magnam.
  Velit quas, at possimus culpa consequatur, suscipit itaque amet deserunt quos quaerat voluptate facere eligendi! Laudantium error, veritatis mollitia quis commodi quaerat magni nisi, perferendis, nesciunt quasi repellat consequuntur deleniti!
  Quidem tempora possimus ab, esse quae ut iste eaque optio exercitationem velit reprehenderit quo! Hic saepe sint at quasi, cumque iste! Voluptatibus cupiditate esse quasi officiis harum mollitia dignissimos ullam.
  Blanditiis repellat reiciendis praesentium officia error illum, sit eaque veritatis quo vitae qui minima et quod dolorem perspiciatis sed impedit incidunt eius excepturi quos aliquam beatae numquam. Illum, iusto deleniti.
  Sit odio voluptatum dolorem porro consequatur alias laudantium eius magni, praesentium rerum ea tenetur atque quidem et temporibus, perspiciatis ipsum quibusdam asperiores soluta ipsa expedita tempora! Distinctio odit aspernatur accusamus.
  Adipisci voluptate labore repudiandae aliquam minima magnam quidem mollitia tenetur commodi. Itaque repellendus architecto eius nisi. Illo aliquid assumenda enim et ratione dicta vel tempore mollitia eaque quibusdam, rerum natus!
  Atque sunt accusantium porro vitae, in error nisi molestias corrupti accusamus necessitatibus dolorem, doloremque labore nam minus explicabo perferendis. Quo at architecto iste eligendi tempora ea, laborum sapiente eius earum.
  Tempora enim cupiditate ducimus optio voluptates deserunt quidem inventore illum sequi amet, reprehenderit molestias adipisci aliquam magni autem voluptate, excepturi, quia recusandae illo cumque at rem? Ipsam, ipsa. Aliquam, repudiandae!
  Molestias dolorem, temporibus, quae earum magnam, praesentium repudiandae labore delectus necessitatibus fuga quis quasi! Nulla ad, odio distinctio doloremque, praesentium impedit modi veritatis non inventore unde, nobis ea aliquid perferendis.
  Quibusdam aliquid cum placeat magni delectus natus at laboriosam, maiores labore nulla ex sed ullam temporibus culpa veniam odio. Aut ea modi quis maxime facere asperiores in necessitatibus, quisquam doloremque.
  Quibusdam dolor expedita, commodi asperiores saepe odit, beatae a modi optio ea possimus. Natus at optio velit dolores amet sed rerum? Sit officia nesciunt, harum aliquid blanditiis praesentium pariatur rerum!")
Post.create!(title: "シドニーの大学進学事情", location: "シドニー", category: "学校", user: milo, description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugit nemo fugiat error illum suscipit dolor! Molestiae natus eum fugit quam aliquam quisquam cumque laborum placeat, dicta quis, dolorum, odit animi.
  Illum recusandae accusamus nam magni, nulla labore pariatur eaque maiores doloremque quae? Reiciendis voluptatum voluptatem praesentium nam odio adipisci autem assumenda voluptatibus similique. Optio, dignissimos sunt itaque delectus iste explicabo.
  Laboriosam fugit, ullam illo autem corporis nihil. Eos voluptas facilis at consectetur nam quia sit perferendis asperiores similique nesciunt, impedit dolorum mollitia, incidunt corrupti optio exercitationem sunt illo ipsum saepe.
  Accusantium eaque officiis voluptatibus quaerat alias, quo vero est nisi, aliquid, fugit dolor aliquam commodi laudantium velit. Consectetur nihil totam, nam eligendi exercitationem in quibusdam neque rerum. Quia, ducimus eum?
  Nostrum assumenda quasi fuga repellat ipsam temporibus illum corrupti, tempore quos deserunt numquam atque, dicta, animi unde reiciendis? Vitae, rem! Iure provident voluptatibus autem dolorum facilis dolores dolore sunt dolor!
  Deserunt possimus sed laudantium quos pariatur animi doloribus, in cumque praesentium. Laborum velit sapiente ratione. Similique, facere voluptatibus iste dolorum laborum nisi est quas veniam quo, consectetur perferendis sint illum.
  Numquam sunt ad soluta porro delectus, temporibus facere dolorem sit? Corporis consequatur neque et perferendis architecto dolorem aspernatur nostrum natus esse eius quisquam, ipsam tempore cumque ex qui ut debitis?
  Temporibus voluptatibus at ipsam quos itaque aut porro, quibusdam accusamus? Dicta est architecto itaque nam eius, facere molestiae! Minima, dolor eos. Magnam ad praesentium consectetur, deserunt consequatur ex nisi saepe?
  Aspernatur excepturi eius minus non repellendus quibusdam culpa perspiciatis enim amet, tempora impedit. Quidem repudiandae vel corrupti architecto officia, dolor accusantium quis temporibus eaque dignissimos, voluptas debitis hic in esse.
  Delectus debitis, voluptatibus perspiciatis quasi beatae rem omnis ad animi modi ducimus, libero illo quaerat eos cupiditate? Reiciendis enim nam labore, corporis provident dolorem tempora vel tenetur culpa a magnam.
  Velit quas, at possimus culpa consequatur, suscipit itaque amet deserunt quos quaerat voluptate facere eligendi! Laudantium error, veritatis mollitia quis commodi quaerat magni nisi, perferendis, nesciunt quasi repellat consequuntur deleniti!
  Quidem tempora possimus ab, esse quae ut iste eaque optio exercitationem velit reprehenderit quo! Hic saepe sint at quasi, cumque iste! Voluptatibus cupiditate esse quasi officiis harum mollitia dignissimos ullam.
  Blanditiis repellat reiciendis praesentium officia error illum, sit eaque veritatis quo vitae qui minima et quod dolorem perspiciatis sed impedit incidunt eius excepturi quos aliquam beatae numquam. Illum, iusto deleniti.
  Sit odio voluptatum dolorem porro consequatur alias laudantium eius magni, praesentium rerum ea tenetur atque quidem et temporibus, perspiciatis ipsum quibusdam asperiores soluta ipsa expedita tempora! Distinctio odit aspernatur accusamus.
  Adipisci voluptate labore repudiandae aliquam minima magnam quidem mollitia tenetur commodi. Itaque repellendus architecto eius nisi. Illo aliquid assumenda enim et ratione dicta vel tempore mollitia eaque quibusdam, rerum natus!
  Atque sunt accusantium porro vitae, in error nisi molestias corrupti accusamus necessitatibus dolorem, doloremque labore nam minus explicabo perferendis. Quo at architecto iste eligendi tempora ea, laborum sapiente eius earum.
  Tempora enim cupiditate ducimus optio voluptates deserunt quidem inventore illum sequi amet, reprehenderit molestias adipisci aliquam magni autem voluptate, excepturi, quia recusandae illo cumque at rem? Ipsam, ipsa. Aliquam, repudiandae!
  Molestias dolorem, temporibus, quae earum magnam, praesentium repudiandae labore delectus necessitatibus fuga quis quasi! Nulla ad, odio distinctio doloremque, praesentium impedit modi veritatis non inventore unde, nobis ea aliquid perferendis.
  Quibusdam aliquid cum placeat magni delectus natus at laboriosam, maiores labore nulla ex sed ullam temporibus culpa veniam odio. Aut ea modi quis maxime facere asperiores in necessitatibus, quisquam doloremque.
  Quibusdam dolor expedita, commodi asperiores saepe odit, beatae a modi optio ea possimus. Natus at optio velit dolores amet sed rerum? Sit officia nesciunt, harum aliquid blanditiis praesentium pariatur rerum!")

Post.create!(title: "フィンランドでの仕事の見つけ方", location: "ヘルシンキ", category: "仕事", user: mana, description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugit nemo fugiat error illum suscipit dolor! Molestiae natus eum fugit quam aliquam quisquam cumque laborum placeat, dicta quis, dolorum, odit animi.
  Illum recusandae accusamus nam magni, nulla labore pariatur eaque maiores doloremque quae? Reiciendis voluptatum voluptatem praesentium nam odio adipisci autem assumenda voluptatibus similique. Optio, dignissimos sunt itaque delectus iste explicabo.
  Laboriosam fugit, ullam illo autem corporis nihil. Eos voluptas facilis at consectetur nam quia sit perferendis asperiores similique nesciunt, impedit dolorum mollitia, incidunt corrupti optio exercitationem sunt illo ipsum saepe.
  Accusantium eaque officiis voluptatibus quaerat alias, quo vero est nisi, aliquid, fugit dolor aliquam commodi laudantium velit. Consectetur nihil totam, nam eligendi exercitationem in quibusdam neque rerum. Quia, ducimus eum?
  Nostrum assumenda quasi fuga repellat ipsam temporibus illum corrupti, tempore quos deserunt numquam atque, dicta, animi unde reiciendis? Vitae, rem! Iure provident voluptatibus autem dolorum facilis dolores dolore sunt dolor!
  Deserunt possimus sed laudantium quos pariatur animi doloribus, in cumque praesentium. Laborum velit sapiente ratione. Similique, facere voluptatibus iste dolorum laborum nisi est quas veniam quo, consectetur perferendis sint illum.
  Numquam sunt ad soluta porro delectus, temporibus facere dolorem sit? Corporis consequatur neque et perferendis architecto dolorem aspernatur nostrum natus esse eius quisquam, ipsam tempore cumque ex qui ut debitis?
  Temporibus voluptatibus at ipsam quos itaque aut porro, quibusdam accusamus? Dicta est architecto itaque nam eius, facere molestiae! Minima, dolor eos. Magnam ad praesentium consectetur, deserunt consequatur ex nisi saepe?
  Aspernatur excepturi eius minus non repellendus quibusdam culpa perspiciatis enim amet, tempora impedit. Quidem repudiandae vel corrupti architecto officia, dolor accusantium quis temporibus eaque dignissimos, voluptas debitis hic in esse.
  Delectus debitis, voluptatibus perspiciatis quasi beatae rem omnis ad animi modi ducimus, libero illo quaerat eos cupiditate? Reiciendis enim nam labore, corporis provident dolorem tempora vel tenetur culpa a magnam.
  Velit quas, at possimus culpa consequatur, suscipit itaque amet deserunt quos quaerat voluptate facere eligendi! Laudantium error, veritatis mollitia quis commodi quaerat magni nisi, perferendis, nesciunt quasi repellat consequuntur deleniti!
  Quidem tempora possimus ab, esse quae ut iste eaque optio exercitationem velit reprehenderit quo! Hic saepe sint at quasi, cumque iste! Voluptatibus cupiditate esse quasi officiis harum mollitia dignissimos ullam.
  Blanditiis repellat reiciendis praesentium officia error illum, sit eaque veritatis quo vitae qui minima et quod dolorem perspiciatis sed impedit incidunt eius excepturi quos aliquam beatae numquam. Illum, iusto deleniti.
  Sit odio voluptatum dolorem porro consequatur alias laudantium eius magni, praesentium rerum ea tenetur atque quidem et temporibus, perspiciatis ipsum quibusdam asperiores soluta ipsa expedita tempora! Distinctio odit aspernatur accusamus.
  Adipisci voluptate labore repudiandae aliquam minima magnam quidem mollitia tenetur commodi. Itaque repellendus architecto eius nisi. Illo aliquid assumenda enim et ratione dicta vel tempore mollitia eaque quibusdam, rerum natus!
  Atque sunt accusantium porro vitae, in error nisi molestias corrupti accusamus necessitatibus dolorem, doloremque labore nam minus explicabo perferendis. Quo at architecto iste eligendi tempora ea, laborum sapiente eius earum.
  Tempora enim cupiditate ducimus optio voluptates deserunt quidem inventore illum sequi amet, reprehenderit molestias adipisci aliquam magni autem voluptate, excepturi, quia recusandae illo cumque at rem? Ipsam, ipsa. Aliquam, repudiandae!
  Molestias dolorem, temporibus, quae earum magnam, praesentium repudiandae labore delectus necessitatibus fuga quis quasi! Nulla ad, odio distinctio doloremque, praesentium impedit modi veritatis non inventore unde, nobis ea aliquid perferendis.
  Quibusdam aliquid cum placeat magni delectus natus at laboriosam, maiores labore nulla ex sed ullam temporibus culpa veniam odio. Aut ea modi quis maxime facere asperiores in necessitatibus, quisquam doloremque.
  Quibusdam dolor expedita, commodi asperiores saepe odit, beatae a modi optio ea possimus. Natus at optio velit dolores amet sed rerum? Sit officia nesciunt, harum aliquid blanditiis praesentium pariatur rerum!")
Post.create!(title: "ミラノのレストランで働くことになりました", location: "ミラノ", category: "仕事", user: mila, description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugit nemo fugiat error illum suscipit dolor! Molestiae natus eum fugit quam aliquam quisquam cumque laborum placeat, dicta quis, dolorum, odit animi.
  Illum recusandae accusamus nam magni, nulla labore pariatur eaque maiores doloremque quae? Reiciendis voluptatum voluptatem praesentium nam odio adipisci autem assumenda voluptatibus similique. Optio, dignissimos sunt itaque delectus iste explicabo.
  Laboriosam fugit, ullam illo autem corporis nihil. Eos voluptas facilis at consectetur nam quia sit perferendis asperiores similique nesciunt, impedit dolorum mollitia, incidunt corrupti optio exercitationem sunt illo ipsum saepe.
  Accusantium eaque officiis voluptatibus quaerat alias, quo vero est nisi, aliquid, fugit dolor aliquam commodi laudantium velit. Consectetur nihil totam, nam eligendi exercitationem in quibusdam neque rerum. Quia, ducimus eum?
  Nostrum assumenda quasi fuga repellat ipsam temporibus illum corrupti, tempore quos deserunt numquam atque, dicta, animi unde reiciendis? Vitae, rem! Iure provident voluptatibus autem dolorum facilis dolores dolore sunt dolor!
  Deserunt possimus sed laudantium quos pariatur animi doloribus, in cumque praesentium. Laborum velit sapiente ratione. Similique, facere voluptatibus iste dolorum laborum nisi est quas veniam quo, consectetur perferendis sint illum.
  Numquam sunt ad soluta porro delectus, temporibus facere dolorem sit? Corporis consequatur neque et perferendis architecto dolorem aspernatur nostrum natus esse eius quisquam, ipsam tempore cumque ex qui ut debitis?
  Temporibus voluptatibus at ipsam quos itaque aut porro, quibusdam accusamus? Dicta est architecto itaque nam eius, facere molestiae! Minima, dolor eos. Magnam ad praesentium consectetur, deserunt consequatur ex nisi saepe?
  Aspernatur excepturi eius minus non repellendus quibusdam culpa perspiciatis enim amet, tempora impedit. Quidem repudiandae vel corrupti architecto officia, dolor accusantium quis temporibus eaque dignissimos, voluptas debitis hic in esse.
  Delectus debitis, voluptatibus perspiciatis quasi beatae rem omnis ad animi modi ducimus, libero illo quaerat eos cupiditate? Reiciendis enim nam labore, corporis provident dolorem tempora vel tenetur culpa a magnam.
  Velit quas, at possimus culpa consequatur, suscipit itaque amet deserunt quos quaerat voluptate facere eligendi! Laudantium error, veritatis mollitia quis commodi quaerat magni nisi, perferendis, nesciunt quasi repellat consequuntur deleniti!
  Quidem tempora possimus ab, esse quae ut iste eaque optio exercitationem velit reprehenderit quo! Hic saepe sint at quasi, cumque iste! Voluptatibus cupiditate esse quasi officiis harum mollitia dignissimos ullam.
  Blanditiis repellat reiciendis praesentium officia error illum, sit eaque veritatis quo vitae qui minima et quod dolorem perspiciatis sed impedit incidunt eius excepturi quos aliquam beatae numquam. Illum, iusto deleniti.
  Sit odio voluptatum dolorem porro consequatur alias laudantium eius magni, praesentium rerum ea tenetur atque quidem et temporibus, perspiciatis ipsum quibusdam asperiores soluta ipsa expedita tempora! Distinctio odit aspernatur accusamus.
  Adipisci voluptate labore repudiandae aliquam minima magnam quidem mollitia tenetur commodi. Itaque repellendus architecto eius nisi. Illo aliquid assumenda enim et ratione dicta vel tempore mollitia eaque quibusdam, rerum natus!
  Atque sunt accusantium porro vitae, in error nisi molestias corrupti accusamus necessitatibus dolorem, doloremque labore nam minus explicabo perferendis. Quo at architecto iste eligendi tempora ea, laborum sapiente eius earum.
  Tempora enim cupiditate ducimus optio voluptates deserunt quidem inventore illum sequi amet, reprehenderit molestias adipisci aliquam magni autem voluptate, excepturi, quia recusandae illo cumque at rem? Ipsam, ipsa. Aliquam, repudiandae!
  Molestias dolorem, temporibus, quae earum magnam, praesentium repudiandae labore delectus necessitatibus fuga quis quasi! Nulla ad, odio distinctio doloremque, praesentium impedit modi veritatis non inventore unde, nobis ea aliquid perferendis.
  Quibusdam aliquid cum placeat magni delectus natus at laboriosam, maiores labore nulla ex sed ullam temporibus culpa veniam odio. Aut ea modi quis maxime facere asperiores in necessitatibus, quisquam doloremque.
  Quibusdam dolor expedita, commodi asperiores saepe odit, beatae a modi optio ea possimus. Natus at optio velit dolores amet sed rerum? Sit officia nesciunt, harum aliquid blanditiis praesentium pariatur rerum!")
Post.create!(title: "ハノイで日本人が多く働いている職種とは", location: "ハノイ", category: "仕事", user: tony, description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugit nemo fugiat error illum suscipit dolor! Molestiae natus eum fugit quam aliquam quisquam cumque laborum placeat, dicta quis, dolorum, odit animi.
  Illum recusandae accusamus nam magni, nulla labore pariatur eaque maiores doloremque quae? Reiciendis voluptatum voluptatem praesentium nam odio adipisci autem assumenda voluptatibus similique. Optio, dignissimos sunt itaque delectus iste explicabo.
  Laboriosam fugit, ullam illo autem corporis nihil. Eos voluptas facilis at consectetur nam quia sit perferendis asperiores similique nesciunt, impedit dolorum mollitia, incidunt corrupti optio exercitationem sunt illo ipsum saepe.
  Accusantium eaque officiis voluptatibus quaerat alias, quo vero est nisi, aliquid, fugit dolor aliquam commodi laudantium velit. Consectetur nihil totam, nam eligendi exercitationem in quibusdam neque rerum. Quia, ducimus eum?
  Nostrum assumenda quasi fuga repellat ipsam temporibus illum corrupti, tempore quos deserunt numquam atque, dicta, animi unde reiciendis? Vitae, rem! Iure provident voluptatibus autem dolorum facilis dolores dolore sunt dolor!
  Deserunt possimus sed laudantium quos pariatur animi doloribus, in cumque praesentium. Laborum velit sapiente ratione. Similique, facere voluptatibus iste dolorum laborum nisi est quas veniam quo, consectetur perferendis sint illum.
  Numquam sunt ad soluta porro delectus, temporibus facere dolorem sit? Corporis consequatur neque et perferendis architecto dolorem aspernatur nostrum natus esse eius quisquam, ipsam tempore cumque ex qui ut debitis?
  Temporibus voluptatibus at ipsam quos itaque aut porro, quibusdam accusamus? Dicta est architecto itaque nam eius, facere molestiae! Minima, dolor eos. Magnam ad praesentium consectetur, deserunt consequatur ex nisi saepe?
  Aspernatur excepturi eius minus non repellendus quibusdam culpa perspiciatis enim amet, tempora impedit. Quidem repudiandae vel corrupti architecto officia, dolor accusantium quis temporibus eaque dignissimos, voluptas debitis hic in esse.
  Delectus debitis, voluptatibus perspiciatis quasi beatae rem omnis ad animi modi ducimus, libero illo quaerat eos cupiditate? Reiciendis enim nam labore, corporis provident dolorem tempora vel tenetur culpa a magnam.
  Velit quas, at possimus culpa consequatur, suscipit itaque amet deserunt quos quaerat voluptate facere eligendi! Laudantium error, veritatis mollitia quis commodi quaerat magni nisi, perferendis, nesciunt quasi repellat consequuntur deleniti!
  Quidem tempora possimus ab, esse quae ut iste eaque optio exercitationem velit reprehenderit quo! Hic saepe sint at quasi, cumque iste! Voluptatibus cupiditate esse quasi officiis harum mollitia dignissimos ullam.
  Blanditiis repellat reiciendis praesentium officia error illum, sit eaque veritatis quo vitae qui minima et quod dolorem perspiciatis sed impedit incidunt eius excepturi quos aliquam beatae numquam. Illum, iusto deleniti.
  Sit odio voluptatum dolorem porro consequatur alias laudantium eius magni, praesentium rerum ea tenetur atque quidem et temporibus, perspiciatis ipsum quibusdam asperiores soluta ipsa expedita tempora! Distinctio odit aspernatur accusamus.
  Adipisci voluptate labore repudiandae aliquam minima magnam quidem mollitia tenetur commodi. Itaque repellendus architecto eius nisi. Illo aliquid assumenda enim et ratione dicta vel tempore mollitia eaque quibusdam, rerum natus!
  Atque sunt accusantium porro vitae, in error nisi molestias corrupti accusamus necessitatibus dolorem, doloremque labore nam minus explicabo perferendis. Quo at architecto iste eligendi tempora ea, laborum sapiente eius earum.
  Tempora enim cupiditate ducimus optio voluptates deserunt quidem inventore illum sequi amet, reprehenderit molestias adipisci aliquam magni autem voluptate, excepturi, quia recusandae illo cumque at rem? Ipsam, ipsa. Aliquam, repudiandae!
  Molestias dolorem, temporibus, quae earum magnam, praesentium repudiandae labore delectus necessitatibus fuga quis quasi! Nulla ad, odio distinctio doloremque, praesentium impedit modi veritatis non inventore unde, nobis ea aliquid perferendis.
  Quibusdam aliquid cum placeat magni delectus natus at laboriosam, maiores labore nulla ex sed ullam temporibus culpa veniam odio. Aut ea modi quis maxime facere asperiores in necessitatibus, quisquam doloremque.
  Quibusdam dolor expedita, commodi asperiores saepe odit, beatae a modi optio ea possimus. Natus at optio velit dolores amet sed rerum? Sit officia nesciunt, harum aliquid blanditiis praesentium pariatur rerum!")
Post.create!(title: "デリーでの仕事探し", location: "デリー", category: "仕事", user: ron, description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugit nemo fugiat error illum suscipit dolor! Molestiae natus eum fugit quam aliquam quisquam cumque laborum placeat, dicta quis, dolorum, odit animi.
  Illum recusandae accusamus nam magni, nulla labore pariatur eaque maiores doloremque quae? Reiciendis voluptatum voluptatem praesentium nam odio adipisci autem assumenda voluptatibus similique. Optio, dignissimos sunt itaque delectus iste explicabo.
  Laboriosam fugit, ullam illo autem corporis nihil. Eos voluptas facilis at consectetur nam quia sit perferendis asperiores similique nesciunt, impedit dolorum mollitia, incidunt corrupti optio exercitationem sunt illo ipsum saepe.
  Accusantium eaque officiis voluptatibus quaerat alias, quo vero est nisi, aliquid, fugit dolor aliquam commodi laudantium velit. Consectetur nihil totam, nam eligendi exercitationem in quibusdam neque rerum. Quia, ducimus eum?
  Nostrum assumenda quasi fuga repellat ipsam temporibus illum corrupti, tempore quos deserunt numquam atque, dicta, animi unde reiciendis? Vitae, rem! Iure provident voluptatibus autem dolorum facilis dolores dolore sunt dolor!
  Deserunt possimus sed laudantium quos pariatur animi doloribus, in cumque praesentium. Laborum velit sapiente ratione. Similique, facere voluptatibus iste dolorum laborum nisi est quas veniam quo, consectetur perferendis sint illum.
  Numquam sunt ad soluta porro delectus, temporibus facere dolorem sit? Corporis consequatur neque et perferendis architecto dolorem aspernatur nostrum natus esse eius quisquam, ipsam tempore cumque ex qui ut debitis?
  Temporibus voluptatibus at ipsam quos itaque aut porro, quibusdam accusamus? Dicta est architecto itaque nam eius, facere molestiae! Minima, dolor eos. Magnam ad praesentium consectetur, deserunt consequatur ex nisi saepe?
  Aspernatur excepturi eius minus non repellendus quibusdam culpa perspiciatis enim amet, tempora impedit. Quidem repudiandae vel corrupti architecto officia, dolor accusantium quis temporibus eaque dignissimos, voluptas debitis hic in esse.
  Delectus debitis, voluptatibus perspiciatis quasi beatae rem omnis ad animi modi ducimus, libero illo quaerat eos cupiditate? Reiciendis enim nam labore, corporis provident dolorem tempora vel tenetur culpa a magnam.
  Velit quas, at possimus culpa consequatur, suscipit itaque amet deserunt quos quaerat voluptate facere eligendi! Laudantium error, veritatis mollitia quis commodi quaerat magni nisi, perferendis, nesciunt quasi repellat consequuntur deleniti!
  Quidem tempora possimus ab, esse quae ut iste eaque optio exercitationem velit reprehenderit quo! Hic saepe sint at quasi, cumque iste! Voluptatibus cupiditate esse quasi officiis harum mollitia dignissimos ullam.
  Blanditiis repellat reiciendis praesentium officia error illum, sit eaque veritatis quo vitae qui minima et quod dolorem perspiciatis sed impedit incidunt eius excepturi quos aliquam beatae numquam. Illum, iusto deleniti.
  Sit odio voluptatum dolorem porro consequatur alias laudantium eius magni, praesentium rerum ea tenetur atque quidem et temporibus, perspiciatis ipsum quibusdam asperiores soluta ipsa expedita tempora! Distinctio odit aspernatur accusamus.
  Adipisci voluptate labore repudiandae aliquam minima magnam quidem mollitia tenetur commodi. Itaque repellendus architecto eius nisi. Illo aliquid assumenda enim et ratione dicta vel tempore mollitia eaque quibusdam, rerum natus!
  Atque sunt accusantium porro vitae, in error nisi molestias corrupti accusamus necessitatibus dolorem, doloremque labore nam minus explicabo perferendis. Quo at architecto iste eligendi tempora ea, laborum sapiente eius earum.
  Tempora enim cupiditate ducimus optio voluptates deserunt quidem inventore illum sequi amet, reprehenderit molestias adipisci aliquam magni autem voluptate, excepturi, quia recusandae illo cumque at rem? Ipsam, ipsa. Aliquam, repudiandae!
  Molestias dolorem, temporibus, quae earum magnam, praesentium repudiandae labore delectus necessitatibus fuga quis quasi! Nulla ad, odio distinctio doloremque, praesentium impedit modi veritatis non inventore unde, nobis ea aliquid perferendis.
  Quibusdam aliquid cum placeat magni delectus natus at laboriosam, maiores labore nulla ex sed ullam temporibus culpa veniam odio. Aut ea modi quis maxime facere asperiores in necessitatibus, quisquam doloremque.
  Quibusdam dolor expedita, commodi asperiores saepe odit, beatae a modi optio ea possimus. Natus at optio velit dolores amet sed rerum? Sit officia nesciunt, harum aliquid blanditiis praesentium pariatur rerum!")
Post.create!(title: "シドニーで日本語教師として働くには", location: "シドニー", category: "仕事", user: milo, description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugit nemo fugiat error illum suscipit dolor! Molestiae natus eum fugit quam aliquam quisquam cumque laborum placeat, dicta quis, dolorum, odit animi.
  Illum recusandae accusamus nam magni, nulla labore pariatur eaque maiores doloremque quae? Reiciendis voluptatum voluptatem praesentium nam odio adipisci autem assumenda voluptatibus similique. Optio, dignissimos sunt itaque delectus iste explicabo.
  Laboriosam fugit, ullam illo autem corporis nihil. Eos voluptas facilis at consectetur nam quia sit perferendis asperiores similique nesciunt, impedit dolorum mollitia, incidunt corrupti optio exercitationem sunt illo ipsum saepe.
  Accusantium eaque officiis voluptatibus quaerat alias, quo vero est nisi, aliquid, fugit dolor aliquam commodi laudantium velit. Consectetur nihil totam, nam eligendi exercitationem in quibusdam neque rerum. Quia, ducimus eum?
  Nostrum assumenda quasi fuga repellat ipsam temporibus illum corrupti, tempore quos deserunt numquam atque, dicta, animi unde reiciendis? Vitae, rem! Iure provident voluptatibus autem dolorum facilis dolores dolore sunt dolor!
  Deserunt possimus sed laudantium quos pariatur animi doloribus, in cumque praesentium. Laborum velit sapiente ratione. Similique, facere voluptatibus iste dolorum laborum nisi est quas veniam quo, consectetur perferendis sint illum.
  Numquam sunt ad soluta porro delectus, temporibus facere dolorem sit? Corporis consequatur neque et perferendis architecto dolorem aspernatur nostrum natus esse eius quisquam, ipsam tempore cumque ex qui ut debitis?
  Temporibus voluptatibus at ipsam quos itaque aut porro, quibusdam accusamus? Dicta est architecto itaque nam eius, facere molestiae! Minima, dolor eos. Magnam ad praesentium consectetur, deserunt consequatur ex nisi saepe?
  Aspernatur excepturi eius minus non repellendus quibusdam culpa perspiciatis enim amet, tempora impedit. Quidem repudiandae vel corrupti architecto officia, dolor accusantium quis temporibus eaque dignissimos, voluptas debitis hic in esse.
  Delectus debitis, voluptatibus perspiciatis quasi beatae rem omnis ad animi modi ducimus, libero illo quaerat eos cupiditate? Reiciendis enim nam labore, corporis provident dolorem tempora vel tenetur culpa a magnam.
  Velit quas, at possimus culpa consequatur, suscipit itaque amet deserunt quos quaerat voluptate facere eligendi! Laudantium error, veritatis mollitia quis commodi quaerat magni nisi, perferendis, nesciunt quasi repellat consequuntur deleniti!
  Quidem tempora possimus ab, esse quae ut iste eaque optio exercitationem velit reprehenderit quo! Hic saepe sint at quasi, cumque iste! Voluptatibus cupiditate esse quasi officiis harum mollitia dignissimos ullam.
  Blanditiis repellat reiciendis praesentium officia error illum, sit eaque veritatis quo vitae qui minima et quod dolorem perspiciatis sed impedit incidunt eius excepturi quos aliquam beatae numquam. Illum, iusto deleniti.
  Sit odio voluptatum dolorem porro consequatur alias laudantium eius magni, praesentium rerum ea tenetur atque quidem et temporibus, perspiciatis ipsum quibusdam asperiores soluta ipsa expedita tempora! Distinctio odit aspernatur accusamus.
  Adipisci voluptate labore repudiandae aliquam minima magnam quidem mollitia tenetur commodi. Itaque repellendus architecto eius nisi. Illo aliquid assumenda enim et ratione dicta vel tempore mollitia eaque quibusdam, rerum natus!
  Atque sunt accusantium porro vitae, in error nisi molestias corrupti accusamus necessitatibus dolorem, doloremque labore nam minus explicabo perferendis. Quo at architecto iste eligendi tempora ea, laborum sapiente eius earum.
  Tempora enim cupiditate ducimus optio voluptates deserunt quidem inventore illum sequi amet, reprehenderit molestias adipisci aliquam magni autem voluptate, excepturi, quia recusandae illo cumque at rem? Ipsam, ipsa. Aliquam, repudiandae!
  Molestias dolorem, temporibus, quae earum magnam, praesentium repudiandae labore delectus necessitatibus fuga quis quasi! Nulla ad, odio distinctio doloremque, praesentium impedit modi veritatis non inventore unde, nobis ea aliquid perferendis.
  Quibusdam aliquid cum placeat magni delectus natus at laboriosam, maiores labore nulla ex sed ullam temporibus culpa veniam odio. Aut ea modi quis maxime facere asperiores in necessitatibus, quisquam doloremque.
  Quibusdam dolor expedita, commodi asperiores saepe odit, beatae a modi optio ea possimus. Natus at optio velit dolores amet sed rerum? Sit officia nesciunt, harum aliquid blanditiis praesentium pariatur rerum!")

  puts "Done! #{User.count} users, #{Post.count} posts, and #{Bookmark.count} bookmarks were created!"
